import { createFileRoute } from "@tanstack/react-router";
import { BarChart3, Users, TrendingUp, Star, CheckCircle2 } from "lucide-react";
import { PageShell } from "@/components/baruna/page/PageShell";
import { trainerPortalNav, EXPERTS_SIDEBAR_META } from "@/data/expertsNav";
import { formatUsp } from "@/lib/trainerModules";
import { useTrainerPortal } from "@/lib/experts/useTrainerPortal";
export const Route=createFileRoute("/experts/portal/analytics")({head:()=>({meta:[{title:"Learner Statistics — Trainer Portal"}]}),component:AnalyticsPage});
function AnalyticsPage(){const q=useTrainerPortal(),d=q.data,t=d?.trainer,countries=d?.analytics?.countries??[],hours=(d?.modules??[]).filter(m=>["approved","published"].includes(m.status)).reduce((n,m)=>n+(m.hours??0),0);if(q.isLoading)return <p className="p-10 text-sm text-muted-foreground">Loading learner statistics…</p>;if(!t)return <p className="p-10 text-sm text-muted-foreground">Learner statistics are unavailable.</p>;const max=Math.max(0,...countries.map(r=>r.participants));return <PageShell sidebar={{...EXPERTS_SIDEBAR_META,title:"Trainer Portal",subtitle:"Learner statistics.",sections:trainerPortalNav("/experts/portal/analytics")}} cta={{icon:BarChart3,title:"Verified metrics only",description:"Unavailable metrics remain clearly marked rather than estimated.",button:"Recognition Framework",href:"/experts/recognition"}}><div className="space-y-6"><div><h1 className="font-display text-3xl font-extrabold text-navy">Learner Statistics</h1><p className="mt-2 text-sm text-muted-foreground">Figures are read from verified trainer and facilitation records.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Metric icon={Users} label="Successful Participants" value={formatUsp(t.uniqueSuccessfulParticipants)}/><Metric icon={TrendingUp} label="Learning Hours Generated" value={formatUsp(hours*t.uniqueSuccessfulParticipants)}/><Metric icon={CheckCircle2} label="Completion Rate" value={d?.analytics?.completionRate==null?"Not available":`${d.analytics.completionRate}%`}/><Metric icon={Star} label="Average Rating" value={d?.analytics?.averageRating==null?"Not available":d.analytics.averageRating.toFixed(1)}/></div><section className="rounded-2xl border border-border bg-card p-6 shadow-soft"><h2 className="font-display text-lg font-bold text-navy">Recorded Participants by Delivery Country</h2>{countries.length?<ul className="mt-4 space-y-2">{countries.map(r=><li key={r.country} className="flex items-center gap-3 text-sm"><span className="w-40 shrink-0 text-navy">{r.country}</span><div className="h-2.5 flex-1 overflow-hidden rounded-full bg-muted"><div className="h-full rounded-full bg-marine" style={{width:`${max?r.participants/max*100:0}%`}}/></div><span className="w-10 text-right text-xs font-bold">{r.participants}</span></li>)}</ul>:<p className="mt-4 rounded-xl border border-dashed p-6 text-center text-sm text-muted-foreground">No country-level facilitation data has been recorded.</p>}</section></div></PageShell>}
function Metric({icon:Icon,label,value}:{icon:React.ElementType;label:string;value:string|number}){return <div className="rounded-2xl border border-border bg-card p-4 shadow-soft"><div className="flex items-center gap-2 text-[0.65rem] font-bold uppercase text-muted-foreground"><Icon className="h-3.5 w-3.5 text-marine"/>{label}</div><p className="mt-2 font-display text-2xl font-extrabold text-navy">{value}</p></div>}
