import { useQuery, useQueryClient } from "@tanstack/react-query";
import { createFileRoute } from "@tanstack/react-router";
import { useServerFn } from "@tanstack/react-start";
import { Inbox, Calendar, MapPin, CheckCircle2 } from "lucide-react";
import { PageShell } from "@/components/baruna/page/PageShell";
import { trainerPortalNav, EXPERTS_SIDEBAR_META } from "@/data/expertsNav";
import { REQUEST_TYPE_CONFIG } from "@/lib/experts";
import { listTrainerServiceRequests, respondToTrainerServiceRequest } from "@/lib/experts/portal-services.functions";
import type { ServiceRequest } from "@/lib/experts/portal-services.types";

export const Route = createFileRoute("/experts/portal/service-requests")({ head: () => ({ meta: [{ title: "Service Requests — Trainer Portal" }, { name: "description", content: "Incoming Expert Service requests directed to you." }] }), component: ServiceRequestsPortal });

const STYLES: Record<string, string> = { confirmed: "bg-eco-community/15 text-eco-community", scheduled: "bg-marine/15 text-marine", under_review: "bg-badge-workshop/15 text-badge-workshop", expert_contacted: "bg-accent/25 text-accent-foreground", declined: "bg-destructive/10 text-destructive" };

function ServiceRequestsPortal() {
  const list = useServerFn(listTrainerServiceRequests); const respond = useServerFn(respondToTrainerServiceRequest); const client = useQueryClient();
  const query = useQuery({ queryKey: ["experts", "trainer-service-requests"], queryFn: () => list(), retry: false });
  const act = async (requestId: string, action: "accept" | "request_info" | "decline") => { await respond({ data: { requestId, action } }); await client.invalidateQueries({ queryKey: ["experts", "trainer-service-requests"] }); await client.invalidateQueries({ queryKey: ["experts", "my-service-requests"] }); };
  return <PageShell sidebar={{ ...EXPERTS_SIDEBAR_META, title: "Trainer Portal", subtitle: "Incoming Expert Services.", sections: trainerPortalNav("/experts/portal/service-requests") }} cta={{ icon: Inbox, title: "Secure request workflow", description: "Every response is recorded in the audit trail.", button: "Back to Dashboard", href: "/experts/portal" }}><div className="space-y-6"><div><h1 className="font-display text-3xl font-extrabold text-navy">Service Requests</h1><p className="mt-2 text-sm text-muted-foreground">Requests submitted directly to your canonical expert profile.</p></div>{query.isLoading ? <p className="p-8 text-center text-sm text-muted-foreground">Loading service requests…</p> : query.isError ? <p className="rounded-xl bg-destructive/10 p-5 text-sm text-destructive">Unable to load trainer service requests.</p> : query.data?.length ? <ul className="space-y-3">{query.data.map((r) => <RequestItem key={r.id} request={r} onAction={act} />)}</ul> : <div className="rounded-2xl border border-dashed border-border bg-card p-12 text-center"><Inbox className="mx-auto h-8 w-8 text-marine" /><p className="mt-3 font-display text-lg font-bold text-navy">No incoming requests</p><p className="mt-1 text-sm text-muted-foreground">Directed service requests will appear here.</p></div>}</div></PageShell>;
}

function RequestItem({ request: r, onAction }: { request: ServiceRequest; onAction: (id: string, action: "accept" | "request_info" | "decline") => Promise<void> }) {
  const values = r.payload.values ?? {}; const topic = values.eventName || values.trainingTitle || values.subjectArea || values.objective || values.technicalIssue || "Expert service request"; const date = values.eventDate || values.trainingDates || values.completionDate || values.timeline || "Date to be agreed"; const place = values.eventFormat || values.deliveryMode || values.country || "To be agreed";
  return <li className="rounded-2xl border border-border bg-card p-5 shadow-soft"><div className="flex flex-wrap items-start justify-between gap-3"><div className="min-w-0 flex-1"><p className="text-[0.65rem] font-bold uppercase tracking-wider text-muted-foreground">{r.requestNumber} · {REQUEST_TYPE_CONFIG[r.type].label}</p><p className="mt-0.5 font-display text-base font-bold text-navy">{topic}</p><p className="mt-1 text-xs text-foreground/70">{values.organization || "Organization not provided"}</p><div className="mt-2 flex flex-wrap gap-3 text-[0.7rem] text-muted-foreground"><span className="inline-flex items-center gap-1"><Calendar className="h-3 w-3" /> {date}</span><span className="inline-flex items-center gap-1"><MapPin className="h-3 w-3" /> {place}</span></div></div><span className={`inline-flex items-center gap-1 rounded-full px-3 py-0.5 text-xs font-bold capitalize ${STYLES[r.status] ?? "bg-muted text-foreground/70"}`}><CheckCircle2 className="h-3 w-3" /> {r.status.replaceAll("_", " ")}</span></div>{!["confirmed", "declined", "completed", "cancelled"].includes(r.status) && <div className="mt-3 flex flex-wrap gap-2"><button onClick={() => void onAction(r.id, "accept")} className="rounded-lg bg-marine px-4 py-1.5 text-xs font-semibold text-white">Accept</button><button onClick={() => void onAction(r.id, "request_info")} className="rounded-lg border border-border px-4 py-1.5 text-xs font-semibold text-navy">Request info</button><button onClick={() => void onAction(r.id, "decline")} className="rounded-lg border border-destructive/40 px-4 py-1.5 text-xs font-semibold text-destructive">Decline</button></div>}</li>;
}
