/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ExpertsRouteImport } from './routes/experts'
import { Route as FellowshipRouteImport } from './routes/fellowship'
import { Route as GovernanceRouteImport } from './routes/governance'
import { Route as HelpRouteImport } from './routes/help'
import { Route as KnowledgeHubRouteImport } from './routes/knowledge-hub'
import { Route as MySubmissionsRouteImport } from './routes/my-submissions'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as PartnershipRouteImport } from './routes/partnership'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AcademyIndexRouteImport } from './routes/academy.index'
import { Route as AcademyAlumniNetworkRouteImport } from './routes/academy.alumni-network'
import { Route as AcademyArchiveRouteImport } from './routes/academy.archive'
import { Route as AcademyCertificationRouteImport } from './routes/academy.certification'
import { Route as AcademyEdition2024RouteImport } from './routes/academy.edition-2024'
import { Route as AcademyLearnRouteImport } from './routes/academy.learn'
import { Route as AcademyProgramsRouteImport } from './routes/academy.programs'
import { Route as AcademyRequestTrainingRouteImport } from './routes/academy.request-training'
import { Route as AcademySelfPacedRouteImport } from './routes/academy.self-paced'
import { Route as AcademyWebinarRouteImport } from './routes/academy.webinar'
import { Route as AcademyWorkshopRouteImport } from './routes/academy.workshop'
import { Route as AccountProfileRouteImport } from './routes/account.profile'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminExpertsRouteImport } from './routes/admin.experts'
import { Route as AdminModulesRouteImport } from './routes/admin.modules'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as EventsIndexRouteImport } from './routes/events.index'
import { Route as EventsSlugRouteImport } from './routes/events.$slug'
import { Route as EventsAllRouteImport } from './routes/events.all'
import { Route as EventsCalendarRouteImport } from './routes/events.calendar'
import { Route as EventsCategoriesRouteImport } from './routes/events.categories'
import { Route as EventsFollowingRouteImport } from './routes/events.following'
import { Route as EventsHostRouteImport } from './routes/events.host'
import { Route as EventsPastRouteImport } from './routes/events.past'
import { Route as EventsRegistrationsRouteImport } from './routes/events.registrations'
import { Route as EventsSavedRouteImport } from './routes/events.saved'
import { Route as EventsScheduleRouteImport } from './routes/events.schedule'
import { Route as EventsSubmitRouteImport } from './routes/events.submit'
import { Route as ExpertsIndexRouteImport } from './routes/experts.index'
import { Route as ExpertsSlugRouteImport } from './routes/experts.$slug'
import { Route as ExpertsBecomeTrainerRouteImport } from './routes/experts.become-trainer'
import { Route as ExpertsContributionsRouteImport } from './routes/experts.contributions'
import { Route as ExpertsDirectoryRouteImport } from './routes/experts.directory'
import { Route as ExpertsFaqsRouteImport } from './routes/experts.faqs'
import { Route as ExpertsJoinRouteImport } from './routes/experts.join'
import { Route as ExpertsMyRequestsRouteImport } from './routes/experts.my-requests'
import { Route as ExpertsPortalRouteImport } from './routes/experts.portal'
import { Route as ExpertsProfileRouteImport } from './routes/experts.profile'
import { Route as ExpertsRecognitionRouteImport } from './routes/experts.recognition'
import { Route as ExpertsRequestRouteImport } from './routes/experts.request'
import { Route as ExpertsServicesRouteImport } from './routes/experts.services'
import { Route as GovernanceIndexRouteImport } from './routes/governance.index'
import { Route as GovernanceDecisionsRouteImport } from './routes/governance.decisions'
import { Route as GovernanceQueueRouteImport } from './routes/governance.queue'
import { Route as GovernanceRolesRouteImport } from './routes/governance.roles'
import { Route as KnowledgeHubTypeRouteImport } from './routes/knowledge-hub_.$type'
import { Route as KnowledgeHubMyContributionsRouteImport } from './routes/knowledge-hub_.my-contributions'
import { Route as KnowledgeHubSubmitResourceRouteImport } from './routes/knowledge-hub_.submit-resource'
import { Route as MySubmissionsIndexRouteImport } from './routes/my-submissions.index'
import { Route as MySubmissionsIdRouteImport } from './routes/my-submissions.$id'
import { Route as MySubmissionsNewRouteImport } from './routes/my-submissions.new'
import { Route as AcademyAlumniIndexRouteImport } from './routes/academy.alumni.index'
import { Route as AcademyAlumniIdRouteImport } from './routes/academy.alumni.$id'
import { Route as AcademyApplicationsIndexRouteImport } from './routes/academy.applications.index'
import { Route as AcademyApplicationsIdRouteImport } from './routes/academy.applications.$id'
import { Route as AcademyApplySlugRouteImport } from './routes/academy.apply.$slug'
import { Route as AcademyCategorySlugRouteImport } from './routes/academy.category.$slug'
import { Route as AcademyCourseOfferingIdRouteImport } from './routes/academy.course.$offeringId'
import { Route as AcademyLearnIndexRouteImport } from './routes/academy.learn.index'
import { Route as AcademyLearnIdRouteImport } from './routes/academy.learn.$id'
import { Route as AcademyLearnAllocatedZonesForAquacultureRouteImport } from './routes/academy.learn.allocated-zones-for-aquaculture'
import { Route as AcademyPathwaysIndexRouteImport } from './routes/academy.pathways.index'
import { Route as AcademyPathwaysSlugRouteImport } from './routes/academy.pathways.$slug'
import { Route as AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRouteImport } from './routes/academy.preview.international-training-fisheries-african-countries'
import { Route as AcademySelfPacedCodeRouteImport } from './routes/academy.self-paced.$code'
import { Route as AcademyShortCoursesIndexRouteImport } from './routes/academy.short-courses.index'
import { Route as AcademyShortCoursesCodeRouteImport } from './routes/academy.short-courses.$code'
import { Route as AcademyTrainingRequestsIndexRouteImport } from './routes/academy.training-requests.index'
import { Route as AcademyTrainingRequestsIdRouteImport } from './routes/academy.training-requests.$id'
import { Route as AcademyTrainingIndexRouteImport } from './routes/academy.training.index'
import { Route as AcademyTrainingSlugRouteImport } from './routes/academy.training.$slug'
import { Route as AcademyTrainingAllocatedZonesForAquacultureRouteImport } from './routes/academy.training.allocated-zones-for-aquaculture'
import { Route as EventsCallsSlugRouteImport } from './routes/events.calls.$slug'
import { Route as EventsCategorySlugRouteImport } from './routes/events.category.$slug'
import { Route as ExpertsPortalIndexRouteImport } from './routes/experts.portal.index'
import { Route as ExpertsPortalAnalyticsRouteImport } from './routes/experts.portal.analytics'
import { Route as ExpertsPortalCertificatesRouteImport } from './routes/experts.portal.certificates'
import { Route as ExpertsPortalPortfolioRouteImport } from './routes/experts.portal.portfolio'
import { Route as ExpertsPortalRecognitionRouteImport } from './routes/experts.portal.recognition'
import { Route as ExpertsPortalReviewStatusRouteImport } from './routes/experts.portal.review-status'
import { Route as ExpertsPortalServiceRequestsRouteImport } from './routes/experts.portal.service-requests'
import { Route as ExpertsPortalSubmitModuleRouteImport } from './routes/experts.portal.submit-module'
import { Route as GovernanceAuditSubjectIdRouteImport } from './routes/governance.audit.$subjectId'
import { Route as GovernanceSubjectIdRouteImport } from './routes/governance.subject.$id'
import { Route as GovernanceSubjectsIndexRouteImport } from './routes/governance.subjects.index'
import { Route as GovernanceSubjectsIdRouteImport } from './routes/governance.subjects.$id'
import { Route as GovernanceTemplatesIndexRouteImport } from './routes/governance.templates.index'
import { Route as GovernanceTemplatesIdRouteImport } from './routes/governance.templates.$id'
import { Route as KnowledgeHubResourceIdRouteImport } from './routes/knowledge-hub_.resource.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpertsRoute = ExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => rootRouteImport,
} as any)
const FellowshipRoute = FellowshipRouteImport.update({
  id: '/fellowship',
  path: '/fellowship',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceRoute = GovernanceRouteImport.update({
  id: '/governance',
  path: '/governance',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubRoute = KnowledgeHubRouteImport.update({
  id: '/knowledge-hub',
  path: '/knowledge-hub',
  getParentRoute: () => rootRouteImport,
} as any)
const MySubmissionsRoute = MySubmissionsRouteImport.update({
  id: '/my-submissions',
  path: '/my-submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnershipRoute = PartnershipRouteImport.update({
  id: '/partnership',
  path: '/partnership',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyIndexRoute = AcademyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAlumniNetworkRoute = AcademyAlumniNetworkRouteImport.update({
  id: '/alumni-network',
  path: '/alumni-network',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyArchiveRoute = AcademyArchiveRouteImport.update({
  id: '/archive',
  path: '/archive',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCertificationRoute = AcademyCertificationRouteImport.update({
  id: '/certification',
  path: '/certification',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyEdition2024Route = AcademyEdition2024RouteImport.update({
  id: '/edition-2024',
  path: '/edition-2024',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLearnRoute = AcademyLearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyProgramsRoute = AcademyProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyRequestTrainingRoute = AcademyRequestTrainingRouteImport.update({
  id: '/request-training',
  path: '/request-training',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademySelfPacedRoute = AcademySelfPacedRouteImport.update({
  id: '/self-paced',
  path: '/self-paced',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyWebinarRoute = AcademyWebinarRouteImport.update({
  id: '/webinar',
  path: '/webinar',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyWorkshopRoute = AcademyWorkshopRouteImport.update({
  id: '/workshop',
  path: '/workshop',
  getParentRoute: () => AcademyRoute,
} as any)
const AccountProfileRoute = AccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminExpertsRoute = AdminExpertsRouteImport.update({
  id: '/experts',
  path: '/experts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModulesRoute = AdminModulesRouteImport.update({
  id: '/modules',
  path: '/modules',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSlugRoute = EventsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const EventsAllRoute = EventsAllRouteImport.update({
  id: '/all',
  path: '/all',
  getParentRoute: () => EventsRoute,
} as any)
const EventsCalendarRoute = EventsCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => EventsRoute,
} as any)
const EventsCategoriesRoute = EventsCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => EventsRoute,
} as any)
const EventsFollowingRoute = EventsFollowingRouteImport.update({
  id: '/following',
  path: '/following',
  getParentRoute: () => EventsRoute,
} as any)
const EventsHostRoute = EventsHostRouteImport.update({
  id: '/host',
  path: '/host',
  getParentRoute: () => EventsRoute,
} as any)
const EventsPastRoute = EventsPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => EventsRoute,
} as any)
const EventsRegistrationsRoute = EventsRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSavedRoute = EventsSavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => EventsRoute,
} as any)
const EventsScheduleRoute = EventsScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => EventsRoute,
} as any)
const EventsSubmitRoute = EventsSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => EventsRoute,
} as any)
const ExpertsIndexRoute = ExpertsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsSlugRoute = ExpertsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsBecomeTrainerRoute = ExpertsBecomeTrainerRouteImport.update({
  id: '/become-trainer',
  path: '/become-trainer',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsContributionsRoute = ExpertsContributionsRouteImport.update({
  id: '/contributions',
  path: '/contributions',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsDirectoryRoute = ExpertsDirectoryRouteImport.update({
  id: '/directory',
  path: '/directory',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsFaqsRoute = ExpertsFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsJoinRoute = ExpertsJoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsMyRequestsRoute = ExpertsMyRequestsRouteImport.update({
  id: '/my-requests',
  path: '/my-requests',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsPortalRoute = ExpertsPortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsProfileRoute = ExpertsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsRecognitionRoute = ExpertsRecognitionRouteImport.update({
  id: '/recognition',
  path: '/recognition',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsRequestRoute = ExpertsRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => ExpertsRoute,
} as any)
const ExpertsServicesRoute = ExpertsServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => ExpertsRoute,
} as any)
const GovernanceIndexRoute = GovernanceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceDecisionsRoute = GovernanceDecisionsRouteImport.update({
  id: '/decisions',
  path: '/decisions',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceQueueRoute = GovernanceQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceRolesRoute = GovernanceRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => GovernanceRoute,
} as any)
const KnowledgeHubTypeRoute = KnowledgeHubTypeRouteImport.update({
  id: '/knowledge-hub_/$type',
  path: '/knowledge-hub/$type',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeHubMyContributionsRoute =
  KnowledgeHubMyContributionsRouteImport.update({
    id: '/knowledge-hub_/my-contributions',
    path: '/knowledge-hub/my-contributions',
    getParentRoute: () => rootRouteImport,
  } as any)
const KnowledgeHubSubmitResourceRoute =
  KnowledgeHubSubmitResourceRouteImport.update({
    id: '/knowledge-hub_/submit-resource',
    path: '/knowledge-hub/submit-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const MySubmissionsIndexRoute = MySubmissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MySubmissionsRoute,
} as any)
const MySubmissionsIdRoute = MySubmissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MySubmissionsRoute,
} as any)
const MySubmissionsNewRoute = MySubmissionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => MySubmissionsRoute,
} as any)
const AcademyAlumniIndexRoute = AcademyAlumniIndexRouteImport.update({
  id: '/alumni/',
  path: '/alumni/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyAlumniIdRoute = AcademyAlumniIdRouteImport.update({
  id: '/alumni/$id',
  path: '/alumni/$id',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyApplicationsIndexRoute =
  AcademyApplicationsIndexRouteImport.update({
    id: '/applications/',
    path: '/applications/',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyApplicationsIdRoute = AcademyApplicationsIdRouteImport.update({
  id: '/applications/$id',
  path: '/applications/$id',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyApplySlugRoute = AcademyApplySlugRouteImport.update({
  id: '/apply/$slug',
  path: '/apply/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCategorySlugRoute = AcademyCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyCourseOfferingIdRoute = AcademyCourseOfferingIdRouteImport.update({
  id: '/course/$offeringId',
  path: '/course/$offeringId',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyLearnIndexRoute = AcademyLearnIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AcademyLearnRoute,
} as any)
const AcademyLearnIdRoute = AcademyLearnIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AcademyLearnRoute,
} as any)
const AcademyLearnAllocatedZonesForAquacultureRoute =
  AcademyLearnAllocatedZonesForAquacultureRouteImport.update({
    id: '/allocated-zones-for-aquaculture',
    path: '/allocated-zones-for-aquaculture',
    getParentRoute: () => AcademyLearnRoute,
  } as any)
const AcademyPathwaysIndexRoute = AcademyPathwaysIndexRouteImport.update({
  id: '/pathways/',
  path: '/pathways/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPathwaysSlugRoute = AcademyPathwaysSlugRouteImport.update({
  id: '/pathways/$slug',
  path: '/pathways/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute =
  AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRouteImport.update(
    {
      id: '/preview/international-training-fisheries-african-countries',
      path: '/preview/international-training-fisheries-african-countries',
      getParentRoute: () => AcademyRoute,
    } as any,
  )
const AcademySelfPacedCodeRoute = AcademySelfPacedCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => AcademySelfPacedRoute,
} as any)
const AcademyShortCoursesIndexRoute =
  AcademyShortCoursesIndexRouteImport.update({
    id: '/short-courses/',
    path: '/short-courses/',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyShortCoursesCodeRoute = AcademyShortCoursesCodeRouteImport.update({
  id: '/short-courses/$code',
  path: '/short-courses/$code',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTrainingRequestsIndexRoute =
  AcademyTrainingRequestsIndexRouteImport.update({
    id: '/training-requests/',
    path: '/training-requests/',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyTrainingRequestsIdRoute =
  AcademyTrainingRequestsIdRouteImport.update({
    id: '/training-requests/$id',
    path: '/training-requests/$id',
    getParentRoute: () => AcademyRoute,
  } as any)
const AcademyTrainingIndexRoute = AcademyTrainingIndexRouteImport.update({
  id: '/training/',
  path: '/training/',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTrainingSlugRoute = AcademyTrainingSlugRouteImport.update({
  id: '/training/$slug',
  path: '/training/$slug',
  getParentRoute: () => AcademyRoute,
} as any)
const AcademyTrainingAllocatedZonesForAquacultureRoute =
  AcademyTrainingAllocatedZonesForAquacultureRouteImport.update({
    id: '/training/allocated-zones-for-aquaculture',
    path: '/training/allocated-zones-for-aquaculture',
    getParentRoute: () => AcademyRoute,
  } as any)
const EventsCallsSlugRoute = EventsCallsSlugRouteImport.update({
  id: '/calls/$slug',
  path: '/calls/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const EventsCategorySlugRoute = EventsCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => EventsRoute,
} as any)
const ExpertsPortalIndexRoute = ExpertsPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExpertsPortalRoute,
} as any)
const ExpertsPortalAnalyticsRoute = ExpertsPortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => ExpertsPortalRoute,
} as any)
const ExpertsPortalCertificatesRoute =
  ExpertsPortalCertificatesRouteImport.update({
    id: '/certificates',
    path: '/certificates',
    getParentRoute: () => ExpertsPortalRoute,
  } as any)
const ExpertsPortalPortfolioRoute = ExpertsPortalPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => ExpertsPortalRoute,
} as any)
const ExpertsPortalRecognitionRoute =
  ExpertsPortalRecognitionRouteImport.update({
    id: '/recognition',
    path: '/recognition',
    getParentRoute: () => ExpertsPortalRoute,
  } as any)
const ExpertsPortalReviewStatusRoute =
  ExpertsPortalReviewStatusRouteImport.update({
    id: '/review-status',
    path: '/review-status',
    getParentRoute: () => ExpertsPortalRoute,
  } as any)
const ExpertsPortalServiceRequestsRoute =
  ExpertsPortalServiceRequestsRouteImport.update({
    id: '/service-requests',
    path: '/service-requests',
    getParentRoute: () => ExpertsPortalRoute,
  } as any)
const ExpertsPortalSubmitModuleRoute =
  ExpertsPortalSubmitModuleRouteImport.update({
    id: '/submit-module',
    path: '/submit-module',
    getParentRoute: () => ExpertsPortalRoute,
  } as any)
const GovernanceAuditSubjectIdRoute =
  GovernanceAuditSubjectIdRouteImport.update({
    id: '/audit/$subjectId',
    path: '/audit/$subjectId',
    getParentRoute: () => GovernanceRoute,
  } as any)
const GovernanceSubjectIdRoute = GovernanceSubjectIdRouteImport.update({
  id: '/subject/$id',
  path: '/subject/$id',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceSubjectsIndexRoute = GovernanceSubjectsIndexRouteImport.update({
  id: '/subjects/',
  path: '/subjects/',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceSubjectsIdRoute = GovernanceSubjectsIdRouteImport.update({
  id: '/subjects/$id',
  path: '/subjects/$id',
  getParentRoute: () => GovernanceRoute,
} as any)
const GovernanceTemplatesIndexRoute =
  GovernanceTemplatesIndexRouteImport.update({
    id: '/templates/',
    path: '/templates/',
    getParentRoute: () => GovernanceRoute,
  } as any)
const GovernanceTemplatesIdRoute = GovernanceTemplatesIdRouteImport.update({
  id: '/templates/$id',
  path: '/templates/$id',
  getParentRoute: () => GovernanceRoute,
} as any)
const KnowledgeHubResourceIdRoute = KnowledgeHubResourceIdRouteImport.update({
  id: '/knowledge-hub_/resource/$id',
  path: '/knowledge-hub/resource/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/events': typeof EventsRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/fellowship': typeof FellowshipRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/help': typeof HelpRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/my-submissions': typeof MySubmissionsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/partnership': typeof PartnershipRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/alumni-network': typeof AcademyAlumniNetworkRoute
  '/academy/archive': typeof AcademyArchiveRoute
  '/academy/certification': typeof AcademyCertificationRoute
  '/academy/edition-2024': typeof AcademyEdition2024Route
  '/academy/learn': typeof AcademyLearnRouteWithChildren
  '/academy/programs': typeof AcademyProgramsRoute
  '/academy/request-training': typeof AcademyRequestTrainingRoute
  '/academy/self-paced': typeof AcademySelfPacedRouteWithChildren
  '/academy/webinar': typeof AcademyWebinarRoute
  '/academy/workshop': typeof AcademyWorkshopRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/all': typeof EventsAllRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/events/following': typeof EventsFollowingRoute
  '/events/host': typeof EventsHostRoute
  '/events/past': typeof EventsPastRoute
  '/events/registrations': typeof EventsRegistrationsRoute
  '/events/saved': typeof EventsSavedRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/submit': typeof EventsSubmitRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/experts/become-trainer': typeof ExpertsBecomeTrainerRoute
  '/experts/contributions': typeof ExpertsContributionsRoute
  '/experts/directory': typeof ExpertsDirectoryRoute
  '/experts/faqs': typeof ExpertsFaqsRoute
  '/experts/join': typeof ExpertsJoinRoute
  '/experts/my-requests': typeof ExpertsMyRequestsRoute
  '/experts/portal': typeof ExpertsPortalRouteWithChildren
  '/experts/profile': typeof ExpertsProfileRoute
  '/experts/recognition': typeof ExpertsRecognitionRoute
  '/experts/request': typeof ExpertsRequestRoute
  '/experts/services': typeof ExpertsServicesRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/queue': typeof GovernanceQueueRoute
  '/governance/roles': typeof GovernanceRolesRoute
  '/knowledge-hub/$type': typeof KnowledgeHubTypeRoute
  '/knowledge-hub/my-contributions': typeof KnowledgeHubMyContributionsRoute
  '/knowledge-hub/submit-resource': typeof KnowledgeHubSubmitResourceRoute
  '/my-submissions/$id': typeof MySubmissionsIdRoute
  '/my-submissions/new': typeof MySubmissionsNewRoute
  '/academy/': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/my-submissions/': typeof MySubmissionsIndexRoute
  '/academy/alumni/$id': typeof AcademyAlumniIdRoute
  '/academy/applications/$id': typeof AcademyApplicationsIdRoute
  '/academy/apply/$slug': typeof AcademyApplySlugRoute
  '/academy/category/$slug': typeof AcademyCategorySlugRoute
  '/academy/course/$offeringId': typeof AcademyCourseOfferingIdRoute
  '/academy/learn/$id': typeof AcademyLearnIdRoute
  '/academy/learn/allocated-zones-for-aquaculture': typeof AcademyLearnAllocatedZonesForAquacultureRoute
  '/academy/pathways/$slug': typeof AcademyPathwaysSlugRoute
  '/academy/preview/international-training-fisheries-african-countries': typeof AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute
  '/academy/self-paced/$code': typeof AcademySelfPacedCodeRoute
  '/academy/short-courses/$code': typeof AcademyShortCoursesCodeRoute
  '/academy/training-requests/$id': typeof AcademyTrainingRequestsIdRoute
  '/academy/training/$slug': typeof AcademyTrainingSlugRoute
  '/academy/training/allocated-zones-for-aquaculture': typeof AcademyTrainingAllocatedZonesForAquacultureRoute
  '/events/calls/$slug': typeof EventsCallsSlugRoute
  '/events/category/$slug': typeof EventsCategorySlugRoute
  '/experts/portal/analytics': typeof ExpertsPortalAnalyticsRoute
  '/experts/portal/certificates': typeof ExpertsPortalCertificatesRoute
  '/experts/portal/portfolio': typeof ExpertsPortalPortfolioRoute
  '/experts/portal/recognition': typeof ExpertsPortalRecognitionRoute
  '/experts/portal/review-status': typeof ExpertsPortalReviewStatusRoute
  '/experts/portal/service-requests': typeof ExpertsPortalServiceRequestsRoute
  '/experts/portal/submit-module': typeof ExpertsPortalSubmitModuleRoute
  '/governance/audit/$subjectId': typeof GovernanceAuditSubjectIdRoute
  '/governance/subject/$id': typeof GovernanceSubjectIdRoute
  '/governance/subjects/$id': typeof GovernanceSubjectsIdRoute
  '/governance/templates/$id': typeof GovernanceTemplatesIdRoute
  '/knowledge-hub/resource/$id': typeof KnowledgeHubResourceIdRoute
  '/academy/alumni/': typeof AcademyAlumniIndexRoute
  '/academy/applications/': typeof AcademyApplicationsIndexRoute
  '/academy/learn/': typeof AcademyLearnIndexRoute
  '/academy/pathways/': typeof AcademyPathwaysIndexRoute
  '/academy/short-courses/': typeof AcademyShortCoursesIndexRoute
  '/academy/training-requests/': typeof AcademyTrainingRequestsIndexRoute
  '/academy/training/': typeof AcademyTrainingIndexRoute
  '/experts/portal/': typeof ExpertsPortalIndexRoute
  '/governance/subjects/': typeof GovernanceSubjectsIndexRoute
  '/governance/templates/': typeof GovernanceTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/account': typeof AccountRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/fellowship': typeof FellowshipRoute
  '/help': typeof HelpRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/notifications': typeof NotificationsRoute
  '/partnership': typeof PartnershipRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/alumni-network': typeof AcademyAlumniNetworkRoute
  '/academy/archive': typeof AcademyArchiveRoute
  '/academy/certification': typeof AcademyCertificationRoute
  '/academy/edition-2024': typeof AcademyEdition2024Route
  '/academy/programs': typeof AcademyProgramsRoute
  '/academy/request-training': typeof AcademyRequestTrainingRoute
  '/academy/self-paced': typeof AcademySelfPacedRouteWithChildren
  '/academy/webinar': typeof AcademyWebinarRoute
  '/academy/workshop': typeof AcademyWorkshopRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/all': typeof EventsAllRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/events/following': typeof EventsFollowingRoute
  '/events/host': typeof EventsHostRoute
  '/events/past': typeof EventsPastRoute
  '/events/registrations': typeof EventsRegistrationsRoute
  '/events/saved': typeof EventsSavedRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/submit': typeof EventsSubmitRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/experts/become-trainer': typeof ExpertsBecomeTrainerRoute
  '/experts/contributions': typeof ExpertsContributionsRoute
  '/experts/directory': typeof ExpertsDirectoryRoute
  '/experts/faqs': typeof ExpertsFaqsRoute
  '/experts/join': typeof ExpertsJoinRoute
  '/experts/my-requests': typeof ExpertsMyRequestsRoute
  '/experts/profile': typeof ExpertsProfileRoute
  '/experts/recognition': typeof ExpertsRecognitionRoute
  '/experts/request': typeof ExpertsRequestRoute
  '/experts/services': typeof ExpertsServicesRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/queue': typeof GovernanceQueueRoute
  '/governance/roles': typeof GovernanceRolesRoute
  '/knowledge-hub/$type': typeof KnowledgeHubTypeRoute
  '/knowledge-hub/my-contributions': typeof KnowledgeHubMyContributionsRoute
  '/knowledge-hub/submit-resource': typeof KnowledgeHubSubmitResourceRoute
  '/my-submissions/$id': typeof MySubmissionsIdRoute
  '/my-submissions/new': typeof MySubmissionsNewRoute
  '/academy': typeof AcademyIndexRoute
  '/admin': typeof AdminIndexRoute
  '/events': typeof EventsIndexRoute
  '/experts': typeof ExpertsIndexRoute
  '/governance': typeof GovernanceIndexRoute
  '/my-submissions': typeof MySubmissionsIndexRoute
  '/academy/alumni/$id': typeof AcademyAlumniIdRoute
  '/academy/applications/$id': typeof AcademyApplicationsIdRoute
  '/academy/apply/$slug': typeof AcademyApplySlugRoute
  '/academy/category/$slug': typeof AcademyCategorySlugRoute
  '/academy/course/$offeringId': typeof AcademyCourseOfferingIdRoute
  '/academy/learn/$id': typeof AcademyLearnIdRoute
  '/academy/learn/allocated-zones-for-aquaculture': typeof AcademyLearnAllocatedZonesForAquacultureRoute
  '/academy/pathways/$slug': typeof AcademyPathwaysSlugRoute
  '/academy/preview/international-training-fisheries-african-countries': typeof AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute
  '/academy/self-paced/$code': typeof AcademySelfPacedCodeRoute
  '/academy/short-courses/$code': typeof AcademyShortCoursesCodeRoute
  '/academy/training-requests/$id': typeof AcademyTrainingRequestsIdRoute
  '/academy/training/$slug': typeof AcademyTrainingSlugRoute
  '/academy/training/allocated-zones-for-aquaculture': typeof AcademyTrainingAllocatedZonesForAquacultureRoute
  '/events/calls/$slug': typeof EventsCallsSlugRoute
  '/events/category/$slug': typeof EventsCategorySlugRoute
  '/experts/portal/analytics': typeof ExpertsPortalAnalyticsRoute
  '/experts/portal/certificates': typeof ExpertsPortalCertificatesRoute
  '/experts/portal/portfolio': typeof ExpertsPortalPortfolioRoute
  '/experts/portal/recognition': typeof ExpertsPortalRecognitionRoute
  '/experts/portal/review-status': typeof ExpertsPortalReviewStatusRoute
  '/experts/portal/service-requests': typeof ExpertsPortalServiceRequestsRoute
  '/experts/portal/submit-module': typeof ExpertsPortalSubmitModuleRoute
  '/governance/audit/$subjectId': typeof GovernanceAuditSubjectIdRoute
  '/governance/subject/$id': typeof GovernanceSubjectIdRoute
  '/governance/subjects/$id': typeof GovernanceSubjectsIdRoute
  '/governance/templates/$id': typeof GovernanceTemplatesIdRoute
  '/knowledge-hub/resource/$id': typeof KnowledgeHubResourceIdRoute
  '/academy/alumni': typeof AcademyAlumniIndexRoute
  '/academy/applications': typeof AcademyApplicationsIndexRoute
  '/academy/learn': typeof AcademyLearnIndexRoute
  '/academy/pathways': typeof AcademyPathwaysIndexRoute
  '/academy/short-courses': typeof AcademyShortCoursesIndexRoute
  '/academy/training-requests': typeof AcademyTrainingRequestsIndexRoute
  '/academy/training': typeof AcademyTrainingIndexRoute
  '/experts/portal': typeof ExpertsPortalIndexRoute
  '/governance/subjects': typeof GovernanceSubjectsIndexRoute
  '/governance/templates': typeof GovernanceTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academy': typeof AcademyRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/analytics': typeof AnalyticsRoute
  '/auth': typeof AuthRoute
  '/community': typeof CommunityRoute
  '/dashboard': typeof DashboardRoute
  '/demo': typeof DemoRoute
  '/events': typeof EventsRouteWithChildren
  '/experts': typeof ExpertsRouteWithChildren
  '/fellowship': typeof FellowshipRoute
  '/governance': typeof GovernanceRouteWithChildren
  '/help': typeof HelpRoute
  '/knowledge-hub': typeof KnowledgeHubRoute
  '/my-submissions': typeof MySubmissionsRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/partnership': typeof PartnershipRoute
  '/saved': typeof SavedRoute
  '/search': typeof SearchRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/academy/alumni-network': typeof AcademyAlumniNetworkRoute
  '/academy/archive': typeof AcademyArchiveRoute
  '/academy/certification': typeof AcademyCertificationRoute
  '/academy/edition-2024': typeof AcademyEdition2024Route
  '/academy/learn': typeof AcademyLearnRouteWithChildren
  '/academy/programs': typeof AcademyProgramsRoute
  '/academy/request-training': typeof AcademyRequestTrainingRoute
  '/academy/self-paced': typeof AcademySelfPacedRouteWithChildren
  '/academy/webinar': typeof AcademyWebinarRoute
  '/academy/workshop': typeof AcademyWorkshopRoute
  '/account/profile': typeof AccountProfileRoute
  '/admin/experts': typeof AdminExpertsRoute
  '/admin/modules': typeof AdminModulesRoute
  '/admin/users': typeof AdminUsersRoute
  '/events/$slug': typeof EventsSlugRoute
  '/events/all': typeof EventsAllRoute
  '/events/calendar': typeof EventsCalendarRoute
  '/events/categories': typeof EventsCategoriesRoute
  '/events/following': typeof EventsFollowingRoute
  '/events/host': typeof EventsHostRoute
  '/events/past': typeof EventsPastRoute
  '/events/registrations': typeof EventsRegistrationsRoute
  '/events/saved': typeof EventsSavedRoute
  '/events/schedule': typeof EventsScheduleRoute
  '/events/submit': typeof EventsSubmitRoute
  '/experts/$slug': typeof ExpertsSlugRoute
  '/experts/become-trainer': typeof ExpertsBecomeTrainerRoute
  '/experts/contributions': typeof ExpertsContributionsRoute
  '/experts/directory': typeof ExpertsDirectoryRoute
  '/experts/faqs': typeof ExpertsFaqsRoute
  '/experts/join': typeof ExpertsJoinRoute
  '/experts/my-requests': typeof ExpertsMyRequestsRoute
  '/experts/portal': typeof ExpertsPortalRouteWithChildren
  '/experts/profile': typeof ExpertsProfileRoute
  '/experts/recognition': typeof ExpertsRecognitionRoute
  '/experts/request': typeof ExpertsRequestRoute
  '/experts/services': typeof ExpertsServicesRoute
  '/governance/decisions': typeof GovernanceDecisionsRoute
  '/governance/queue': typeof GovernanceQueueRoute
  '/governance/roles': typeof GovernanceRolesRoute
  '/knowledge-hub_/$type': typeof KnowledgeHubTypeRoute
  '/knowledge-hub_/my-contributions': typeof KnowledgeHubMyContributionsRoute
  '/knowledge-hub_/submit-resource': typeof KnowledgeHubSubmitResourceRoute
  '/my-submissions/$id': typeof MySubmissionsIdRoute
  '/my-submissions/new': typeof MySubmissionsNewRoute
  '/academy/': typeof AcademyIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/events/': typeof EventsIndexRoute
  '/experts/': typeof ExpertsIndexRoute
  '/governance/': typeof GovernanceIndexRoute
  '/my-submissions/': typeof MySubmissionsIndexRoute
  '/academy/alumni/$id': typeof AcademyAlumniIdRoute
  '/academy/applications/$id': typeof AcademyApplicationsIdRoute
  '/academy/apply/$slug': typeof AcademyApplySlugRoute
  '/academy/category/$slug': typeof AcademyCategorySlugRoute
  '/academy/course/$offeringId': typeof AcademyCourseOfferingIdRoute
  '/academy/learn/$id': typeof AcademyLearnIdRoute
  '/academy/learn/allocated-zones-for-aquaculture': typeof AcademyLearnAllocatedZonesForAquacultureRoute
  '/academy/pathways/$slug': typeof AcademyPathwaysSlugRoute
  '/academy/preview/international-training-fisheries-african-countries': typeof AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute
  '/academy/self-paced/$code': typeof AcademySelfPacedCodeRoute
  '/academy/short-courses/$code': typeof AcademyShortCoursesCodeRoute
  '/academy/training-requests/$id': typeof AcademyTrainingRequestsIdRoute
  '/academy/training/$slug': typeof AcademyTrainingSlugRoute
  '/academy/training/allocated-zones-for-aquaculture': typeof AcademyTrainingAllocatedZonesForAquacultureRoute
  '/events/calls/$slug': typeof EventsCallsSlugRoute
  '/events/category/$slug': typeof EventsCategorySlugRoute
  '/experts/portal/analytics': typeof ExpertsPortalAnalyticsRoute
  '/experts/portal/certificates': typeof ExpertsPortalCertificatesRoute
  '/experts/portal/portfolio': typeof ExpertsPortalPortfolioRoute
  '/experts/portal/recognition': typeof ExpertsPortalRecognitionRoute
  '/experts/portal/review-status': typeof ExpertsPortalReviewStatusRoute
  '/experts/portal/service-requests': typeof ExpertsPortalServiceRequestsRoute
  '/experts/portal/submit-module': typeof ExpertsPortalSubmitModuleRoute
  '/governance/audit/$subjectId': typeof GovernanceAuditSubjectIdRoute
  '/governance/subject/$id': typeof GovernanceSubjectIdRoute
  '/governance/subjects/$id': typeof GovernanceSubjectsIdRoute
  '/governance/templates/$id': typeof GovernanceTemplatesIdRoute
  '/knowledge-hub_/resource/$id': typeof KnowledgeHubResourceIdRoute
  '/academy/alumni/': typeof AcademyAlumniIndexRoute
  '/academy/applications/': typeof AcademyApplicationsIndexRoute
  '/academy/learn/': typeof AcademyLearnIndexRoute
  '/academy/pathways/': typeof AcademyPathwaysIndexRoute
  '/academy/short-courses/': typeof AcademyShortCoursesIndexRoute
  '/academy/training-requests/': typeof AcademyTrainingRequestsIndexRoute
  '/academy/training/': typeof AcademyTrainingIndexRoute
  '/experts/portal/': typeof ExpertsPortalIndexRoute
  '/governance/subjects/': typeof GovernanceSubjectsIndexRoute
  '/governance/templates/': typeof GovernanceTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academy'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/events'
    | '/experts'
    | '/fellowship'
    | '/governance'
    | '/help'
    | '/knowledge-hub'
    | '/my-submissions'
    | '/notifications'
    | '/partnership'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/academy/alumni-network'
    | '/academy/archive'
    | '/academy/certification'
    | '/academy/edition-2024'
    | '/academy/learn'
    | '/academy/programs'
    | '/academy/request-training'
    | '/academy/self-paced'
    | '/academy/webinar'
    | '/academy/workshop'
    | '/account/profile'
    | '/admin/experts'
    | '/admin/modules'
    | '/admin/users'
    | '/events/$slug'
    | '/events/all'
    | '/events/calendar'
    | '/events/categories'
    | '/events/following'
    | '/events/host'
    | '/events/past'
    | '/events/registrations'
    | '/events/saved'
    | '/events/schedule'
    | '/events/submit'
    | '/experts/$slug'
    | '/experts/become-trainer'
    | '/experts/contributions'
    | '/experts/directory'
    | '/experts/faqs'
    | '/experts/join'
    | '/experts/my-requests'
    | '/experts/portal'
    | '/experts/profile'
    | '/experts/recognition'
    | '/experts/request'
    | '/experts/services'
    | '/governance/decisions'
    | '/governance/queue'
    | '/governance/roles'
    | '/knowledge-hub/$type'
    | '/knowledge-hub/my-contributions'
    | '/knowledge-hub/submit-resource'
    | '/my-submissions/$id'
    | '/my-submissions/new'
    | '/academy/'
    | '/admin/'
    | '/events/'
    | '/experts/'
    | '/governance/'
    | '/my-submissions/'
    | '/academy/alumni/$id'
    | '/academy/applications/$id'
    | '/academy/apply/$slug'
    | '/academy/category/$slug'
    | '/academy/course/$offeringId'
    | '/academy/learn/$id'
    | '/academy/learn/allocated-zones-for-aquaculture'
    | '/academy/pathways/$slug'
    | '/academy/preview/international-training-fisheries-african-countries'
    | '/academy/self-paced/$code'
    | '/academy/short-courses/$code'
    | '/academy/training-requests/$id'
    | '/academy/training/$slug'
    | '/academy/training/allocated-zones-for-aquaculture'
    | '/events/calls/$slug'
    | '/events/category/$slug'
    | '/experts/portal/analytics'
    | '/experts/portal/certificates'
    | '/experts/portal/portfolio'
    | '/experts/portal/recognition'
    | '/experts/portal/review-status'
    | '/experts/portal/service-requests'
    | '/experts/portal/submit-module'
    | '/governance/audit/$subjectId'
    | '/governance/subject/$id'
    | '/governance/subjects/$id'
    | '/governance/templates/$id'
    | '/knowledge-hub/resource/$id'
    | '/academy/alumni/'
    | '/academy/applications/'
    | '/academy/learn/'
    | '/academy/pathways/'
    | '/academy/short-courses/'
    | '/academy/training-requests/'
    | '/academy/training/'
    | '/experts/portal/'
    | '/governance/subjects/'
    | '/governance/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/account'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/fellowship'
    | '/help'
    | '/knowledge-hub'
    | '/notifications'
    | '/partnership'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/academy/alumni-network'
    | '/academy/archive'
    | '/academy/certification'
    | '/academy/edition-2024'
    | '/academy/programs'
    | '/academy/request-training'
    | '/academy/self-paced'
    | '/academy/webinar'
    | '/academy/workshop'
    | '/account/profile'
    | '/admin/experts'
    | '/admin/modules'
    | '/admin/users'
    | '/events/$slug'
    | '/events/all'
    | '/events/calendar'
    | '/events/categories'
    | '/events/following'
    | '/events/host'
    | '/events/past'
    | '/events/registrations'
    | '/events/saved'
    | '/events/schedule'
    | '/events/submit'
    | '/experts/$slug'
    | '/experts/become-trainer'
    | '/experts/contributions'
    | '/experts/directory'
    | '/experts/faqs'
    | '/experts/join'
    | '/experts/my-requests'
    | '/experts/profile'
    | '/experts/recognition'
    | '/experts/request'
    | '/experts/services'
    | '/governance/decisions'
    | '/governance/queue'
    | '/governance/roles'
    | '/knowledge-hub/$type'
    | '/knowledge-hub/my-contributions'
    | '/knowledge-hub/submit-resource'
    | '/my-submissions/$id'
    | '/my-submissions/new'
    | '/academy'
    | '/admin'
    | '/events'
    | '/experts'
    | '/governance'
    | '/my-submissions'
    | '/academy/alumni/$id'
    | '/academy/applications/$id'
    | '/academy/apply/$slug'
    | '/academy/category/$slug'
    | '/academy/course/$offeringId'
    | '/academy/learn/$id'
    | '/academy/learn/allocated-zones-for-aquaculture'
    | '/academy/pathways/$slug'
    | '/academy/preview/international-training-fisheries-african-countries'
    | '/academy/self-paced/$code'
    | '/academy/short-courses/$code'
    | '/academy/training-requests/$id'
    | '/academy/training/$slug'
    | '/academy/training/allocated-zones-for-aquaculture'
    | '/events/calls/$slug'
    | '/events/category/$slug'
    | '/experts/portal/analytics'
    | '/experts/portal/certificates'
    | '/experts/portal/portfolio'
    | '/experts/portal/recognition'
    | '/experts/portal/review-status'
    | '/experts/portal/service-requests'
    | '/experts/portal/submit-module'
    | '/governance/audit/$subjectId'
    | '/governance/subject/$id'
    | '/governance/subjects/$id'
    | '/governance/templates/$id'
    | '/knowledge-hub/resource/$id'
    | '/academy/alumni'
    | '/academy/applications'
    | '/academy/learn'
    | '/academy/pathways'
    | '/academy/short-courses'
    | '/academy/training-requests'
    | '/academy/training'
    | '/experts/portal'
    | '/governance/subjects'
    | '/governance/templates'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academy'
    | '/account'
    | '/admin'
    | '/analytics'
    | '/auth'
    | '/community'
    | '/dashboard'
    | '/demo'
    | '/events'
    | '/experts'
    | '/fellowship'
    | '/governance'
    | '/help'
    | '/knowledge-hub'
    | '/my-submissions'
    | '/notifications'
    | '/partnership'
    | '/saved'
    | '/search'
    | '/sitemap.xml'
    | '/academy/alumni-network'
    | '/academy/archive'
    | '/academy/certification'
    | '/academy/edition-2024'
    | '/academy/learn'
    | '/academy/programs'
    | '/academy/request-training'
    | '/academy/self-paced'
    | '/academy/webinar'
    | '/academy/workshop'
    | '/account/profile'
    | '/admin/experts'
    | '/admin/modules'
    | '/admin/users'
    | '/events/$slug'
    | '/events/all'
    | '/events/calendar'
    | '/events/categories'
    | '/events/following'
    | '/events/host'
    | '/events/past'
    | '/events/registrations'
    | '/events/saved'
    | '/events/schedule'
    | '/events/submit'
    | '/experts/$slug'
    | '/experts/become-trainer'
    | '/experts/contributions'
    | '/experts/directory'
    | '/experts/faqs'
    | '/experts/join'
    | '/experts/my-requests'
    | '/experts/portal'
    | '/experts/profile'
    | '/experts/recognition'
    | '/experts/request'
    | '/experts/services'
    | '/governance/decisions'
    | '/governance/queue'
    | '/governance/roles'
    | '/knowledge-hub_/$type'
    | '/knowledge-hub_/my-contributions'
    | '/knowledge-hub_/submit-resource'
    | '/my-submissions/$id'
    | '/my-submissions/new'
    | '/academy/'
    | '/admin/'
    | '/events/'
    | '/experts/'
    | '/governance/'
    | '/my-submissions/'
    | '/academy/alumni/$id'
    | '/academy/applications/$id'
    | '/academy/apply/$slug'
    | '/academy/category/$slug'
    | '/academy/course/$offeringId'
    | '/academy/learn/$id'
    | '/academy/learn/allocated-zones-for-aquaculture'
    | '/academy/pathways/$slug'
    | '/academy/preview/international-training-fisheries-african-countries'
    | '/academy/self-paced/$code'
    | '/academy/short-courses/$code'
    | '/academy/training-requests/$id'
    | '/academy/training/$slug'
    | '/academy/training/allocated-zones-for-aquaculture'
    | '/events/calls/$slug'
    | '/events/category/$slug'
    | '/experts/portal/analytics'
    | '/experts/portal/certificates'
    | '/experts/portal/portfolio'
    | '/experts/portal/recognition'
    | '/experts/portal/review-status'
    | '/experts/portal/service-requests'
    | '/experts/portal/submit-module'
    | '/governance/audit/$subjectId'
    | '/governance/subject/$id'
    | '/governance/subjects/$id'
    | '/governance/templates/$id'
    | '/knowledge-hub_/resource/$id'
    | '/academy/alumni/'
    | '/academy/applications/'
    | '/academy/learn/'
    | '/academy/pathways/'
    | '/academy/short-courses/'
    | '/academy/training-requests/'
    | '/academy/training/'
    | '/experts/portal/'
    | '/governance/subjects/'
    | '/governance/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AnalyticsRoute: typeof AnalyticsRoute
  AuthRoute: typeof AuthRoute
  CommunityRoute: typeof CommunityRoute
  DashboardRoute: typeof DashboardRoute
  DemoRoute: typeof DemoRoute
  EventsRoute: typeof EventsRouteWithChildren
  ExpertsRoute: typeof ExpertsRouteWithChildren
  FellowshipRoute: typeof FellowshipRoute
  GovernanceRoute: typeof GovernanceRouteWithChildren
  HelpRoute: typeof HelpRoute
  KnowledgeHubRoute: typeof KnowledgeHubRoute
  MySubmissionsRoute: typeof MySubmissionsRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PartnershipRoute: typeof PartnershipRoute
  SavedRoute: typeof SavedRoute
  SearchRoute: typeof SearchRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KnowledgeHubTypeRoute: typeof KnowledgeHubTypeRoute
  KnowledgeHubMyContributionsRoute: typeof KnowledgeHubMyContributionsRoute
  KnowledgeHubSubmitResourceRoute: typeof KnowledgeHubSubmitResourceRoute
  KnowledgeHubResourceIdRoute: typeof KnowledgeHubResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experts': {
      id: '/experts'
      path: '/experts'
      fullPath: '/experts'
      preLoaderRoute: typeof ExpertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fellowship': {
      id: '/fellowship'
      path: '/fellowship'
      fullPath: '/fellowship'
      preLoaderRoute: typeof FellowshipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance': {
      id: '/governance'
      path: '/governance'
      fullPath: '/governance'
      preLoaderRoute: typeof GovernanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub': {
      id: '/knowledge-hub'
      path: '/knowledge-hub'
      fullPath: '/knowledge-hub'
      preLoaderRoute: typeof KnowledgeHubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions': {
      id: '/my-submissions'
      path: '/my-submissions'
      fullPath: '/my-submissions'
      preLoaderRoute: typeof MySubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partnership': {
      id: '/partnership'
      path: '/partnership'
      fullPath: '/partnership'
      preLoaderRoute: typeof PartnershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/': {
      id: '/academy/'
      path: '/'
      fullPath: '/academy/'
      preLoaderRoute: typeof AcademyIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/alumni-network': {
      id: '/academy/alumni-network'
      path: '/alumni-network'
      fullPath: '/academy/alumni-network'
      preLoaderRoute: typeof AcademyAlumniNetworkRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/archive': {
      id: '/academy/archive'
      path: '/archive'
      fullPath: '/academy/archive'
      preLoaderRoute: typeof AcademyArchiveRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/certification': {
      id: '/academy/certification'
      path: '/certification'
      fullPath: '/academy/certification'
      preLoaderRoute: typeof AcademyCertificationRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/edition-2024': {
      id: '/academy/edition-2024'
      path: '/edition-2024'
      fullPath: '/academy/edition-2024'
      preLoaderRoute: typeof AcademyEdition2024RouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/learn': {
      id: '/academy/learn'
      path: '/learn'
      fullPath: '/academy/learn'
      preLoaderRoute: typeof AcademyLearnRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/programs': {
      id: '/academy/programs'
      path: '/programs'
      fullPath: '/academy/programs'
      preLoaderRoute: typeof AcademyProgramsRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/request-training': {
      id: '/academy/request-training'
      path: '/request-training'
      fullPath: '/academy/request-training'
      preLoaderRoute: typeof AcademyRequestTrainingRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/self-paced': {
      id: '/academy/self-paced'
      path: '/self-paced'
      fullPath: '/academy/self-paced'
      preLoaderRoute: typeof AcademySelfPacedRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/webinar': {
      id: '/academy/webinar'
      path: '/webinar'
      fullPath: '/academy/webinar'
      preLoaderRoute: typeof AcademyWebinarRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/workshop': {
      id: '/academy/workshop'
      path: '/workshop'
      fullPath: '/academy/workshop'
      preLoaderRoute: typeof AcademyWorkshopRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/account/profile': {
      id: '/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AccountProfileRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/experts': {
      id: '/admin/experts'
      path: '/experts'
      fullPath: '/admin/experts'
      preLoaderRoute: typeof AdminExpertsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/modules': {
      id: '/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AdminModulesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/events/': {
      id: '/events/'
      path: '/'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/$slug': {
      id: '/events/$slug'
      path: '/$slug'
      fullPath: '/events/$slug'
      preLoaderRoute: typeof EventsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/all': {
      id: '/events/all'
      path: '/all'
      fullPath: '/events/all'
      preLoaderRoute: typeof EventsAllRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/calendar': {
      id: '/events/calendar'
      path: '/calendar'
      fullPath: '/events/calendar'
      preLoaderRoute: typeof EventsCalendarRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/categories': {
      id: '/events/categories'
      path: '/categories'
      fullPath: '/events/categories'
      preLoaderRoute: typeof EventsCategoriesRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/following': {
      id: '/events/following'
      path: '/following'
      fullPath: '/events/following'
      preLoaderRoute: typeof EventsFollowingRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/host': {
      id: '/events/host'
      path: '/host'
      fullPath: '/events/host'
      preLoaderRoute: typeof EventsHostRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/past': {
      id: '/events/past'
      path: '/past'
      fullPath: '/events/past'
      preLoaderRoute: typeof EventsPastRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/registrations': {
      id: '/events/registrations'
      path: '/registrations'
      fullPath: '/events/registrations'
      preLoaderRoute: typeof EventsRegistrationsRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/saved': {
      id: '/events/saved'
      path: '/saved'
      fullPath: '/events/saved'
      preLoaderRoute: typeof EventsSavedRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/schedule': {
      id: '/events/schedule'
      path: '/schedule'
      fullPath: '/events/schedule'
      preLoaderRoute: typeof EventsScheduleRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/submit': {
      id: '/events/submit'
      path: '/submit'
      fullPath: '/events/submit'
      preLoaderRoute: typeof EventsSubmitRouteImport
      parentRoute: typeof EventsRoute
    }
    '/experts/': {
      id: '/experts/'
      path: '/'
      fullPath: '/experts/'
      preLoaderRoute: typeof ExpertsIndexRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/$slug': {
      id: '/experts/$slug'
      path: '/$slug'
      fullPath: '/experts/$slug'
      preLoaderRoute: typeof ExpertsSlugRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/become-trainer': {
      id: '/experts/become-trainer'
      path: '/become-trainer'
      fullPath: '/experts/become-trainer'
      preLoaderRoute: typeof ExpertsBecomeTrainerRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/contributions': {
      id: '/experts/contributions'
      path: '/contributions'
      fullPath: '/experts/contributions'
      preLoaderRoute: typeof ExpertsContributionsRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/directory': {
      id: '/experts/directory'
      path: '/directory'
      fullPath: '/experts/directory'
      preLoaderRoute: typeof ExpertsDirectoryRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/faqs': {
      id: '/experts/faqs'
      path: '/faqs'
      fullPath: '/experts/faqs'
      preLoaderRoute: typeof ExpertsFaqsRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/join': {
      id: '/experts/join'
      path: '/join'
      fullPath: '/experts/join'
      preLoaderRoute: typeof ExpertsJoinRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/my-requests': {
      id: '/experts/my-requests'
      path: '/my-requests'
      fullPath: '/experts/my-requests'
      preLoaderRoute: typeof ExpertsMyRequestsRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/portal': {
      id: '/experts/portal'
      path: '/portal'
      fullPath: '/experts/portal'
      preLoaderRoute: typeof ExpertsPortalRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/profile': {
      id: '/experts/profile'
      path: '/profile'
      fullPath: '/experts/profile'
      preLoaderRoute: typeof ExpertsProfileRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/recognition': {
      id: '/experts/recognition'
      path: '/recognition'
      fullPath: '/experts/recognition'
      preLoaderRoute: typeof ExpertsRecognitionRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/request': {
      id: '/experts/request'
      path: '/request'
      fullPath: '/experts/request'
      preLoaderRoute: typeof ExpertsRequestRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/experts/services': {
      id: '/experts/services'
      path: '/services'
      fullPath: '/experts/services'
      preLoaderRoute: typeof ExpertsServicesRouteImport
      parentRoute: typeof ExpertsRoute
    }
    '/governance/': {
      id: '/governance/'
      path: '/'
      fullPath: '/governance/'
      preLoaderRoute: typeof GovernanceIndexRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/decisions': {
      id: '/governance/decisions'
      path: '/decisions'
      fullPath: '/governance/decisions'
      preLoaderRoute: typeof GovernanceDecisionsRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/queue': {
      id: '/governance/queue'
      path: '/queue'
      fullPath: '/governance/queue'
      preLoaderRoute: typeof GovernanceQueueRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/roles': {
      id: '/governance/roles'
      path: '/roles'
      fullPath: '/governance/roles'
      preLoaderRoute: typeof GovernanceRolesRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/knowledge-hub_/$type': {
      id: '/knowledge-hub_/$type'
      path: '/knowledge-hub/$type'
      fullPath: '/knowledge-hub/$type'
      preLoaderRoute: typeof KnowledgeHubTypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub_/my-contributions': {
      id: '/knowledge-hub_/my-contributions'
      path: '/knowledge-hub/my-contributions'
      fullPath: '/knowledge-hub/my-contributions'
      preLoaderRoute: typeof KnowledgeHubMyContributionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-hub_/submit-resource': {
      id: '/knowledge-hub_/submit-resource'
      path: '/knowledge-hub/submit-resource'
      fullPath: '/knowledge-hub/submit-resource'
      preLoaderRoute: typeof KnowledgeHubSubmitResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-submissions/': {
      id: '/my-submissions/'
      path: '/'
      fullPath: '/my-submissions/'
      preLoaderRoute: typeof MySubmissionsIndexRouteImport
      parentRoute: typeof MySubmissionsRoute
    }
    '/my-submissions/$id': {
      id: '/my-submissions/$id'
      path: '/$id'
      fullPath: '/my-submissions/$id'
      preLoaderRoute: typeof MySubmissionsIdRouteImport
      parentRoute: typeof MySubmissionsRoute
    }
    '/my-submissions/new': {
      id: '/my-submissions/new'
      path: '/new'
      fullPath: '/my-submissions/new'
      preLoaderRoute: typeof MySubmissionsNewRouteImport
      parentRoute: typeof MySubmissionsRoute
    }
    '/academy/alumni/': {
      id: '/academy/alumni/'
      path: '/alumni'
      fullPath: '/academy/alumni/'
      preLoaderRoute: typeof AcademyAlumniIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/alumni/$id': {
      id: '/academy/alumni/$id'
      path: '/alumni/$id'
      fullPath: '/academy/alumni/$id'
      preLoaderRoute: typeof AcademyAlumniIdRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/applications/': {
      id: '/academy/applications/'
      path: '/applications'
      fullPath: '/academy/applications/'
      preLoaderRoute: typeof AcademyApplicationsIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/applications/$id': {
      id: '/academy/applications/$id'
      path: '/applications/$id'
      fullPath: '/academy/applications/$id'
      preLoaderRoute: typeof AcademyApplicationsIdRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/apply/$slug': {
      id: '/academy/apply/$slug'
      path: '/apply/$slug'
      fullPath: '/academy/apply/$slug'
      preLoaderRoute: typeof AcademyApplySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/category/$slug': {
      id: '/academy/category/$slug'
      path: '/category/$slug'
      fullPath: '/academy/category/$slug'
      preLoaderRoute: typeof AcademyCategorySlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/course/$offeringId': {
      id: '/academy/course/$offeringId'
      path: '/course/$offeringId'
      fullPath: '/academy/course/$offeringId'
      preLoaderRoute: typeof AcademyCourseOfferingIdRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/learn/': {
      id: '/academy/learn/'
      path: '/'
      fullPath: '/academy/learn/'
      preLoaderRoute: typeof AcademyLearnIndexRouteImport
      parentRoute: typeof AcademyLearnRoute
    }
    '/academy/learn/$id': {
      id: '/academy/learn/$id'
      path: '/$id'
      fullPath: '/academy/learn/$id'
      preLoaderRoute: typeof AcademyLearnIdRouteImport
      parentRoute: typeof AcademyLearnRoute
    }
    '/academy/learn/allocated-zones-for-aquaculture': {
      id: '/academy/learn/allocated-zones-for-aquaculture'
      path: '/allocated-zones-for-aquaculture'
      fullPath: '/academy/learn/allocated-zones-for-aquaculture'
      preLoaderRoute: typeof AcademyLearnAllocatedZonesForAquacultureRouteImport
      parentRoute: typeof AcademyLearnRoute
    }
    '/academy/pathways/': {
      id: '/academy/pathways/'
      path: '/pathways'
      fullPath: '/academy/pathways/'
      preLoaderRoute: typeof AcademyPathwaysIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/pathways/$slug': {
      id: '/academy/pathways/$slug'
      path: '/pathways/$slug'
      fullPath: '/academy/pathways/$slug'
      preLoaderRoute: typeof AcademyPathwaysSlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/preview/international-training-fisheries-african-countries': {
      id: '/academy/preview/international-training-fisheries-african-countries'
      path: '/preview/international-training-fisheries-african-countries'
      fullPath: '/academy/preview/international-training-fisheries-african-countries'
      preLoaderRoute: typeof AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/self-paced/$code': {
      id: '/academy/self-paced/$code'
      path: '/$code'
      fullPath: '/academy/self-paced/$code'
      preLoaderRoute: typeof AcademySelfPacedCodeRouteImport
      parentRoute: typeof AcademySelfPacedRoute
    }
    '/academy/short-courses/': {
      id: '/academy/short-courses/'
      path: '/short-courses'
      fullPath: '/academy/short-courses/'
      preLoaderRoute: typeof AcademyShortCoursesIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/short-courses/$code': {
      id: '/academy/short-courses/$code'
      path: '/short-courses/$code'
      fullPath: '/academy/short-courses/$code'
      preLoaderRoute: typeof AcademyShortCoursesCodeRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/training-requests/': {
      id: '/academy/training-requests/'
      path: '/training-requests'
      fullPath: '/academy/training-requests/'
      preLoaderRoute: typeof AcademyTrainingRequestsIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/training-requests/$id': {
      id: '/academy/training-requests/$id'
      path: '/training-requests/$id'
      fullPath: '/academy/training-requests/$id'
      preLoaderRoute: typeof AcademyTrainingRequestsIdRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/training/': {
      id: '/academy/training/'
      path: '/training'
      fullPath: '/academy/training/'
      preLoaderRoute: typeof AcademyTrainingIndexRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/training/$slug': {
      id: '/academy/training/$slug'
      path: '/training/$slug'
      fullPath: '/academy/training/$slug'
      preLoaderRoute: typeof AcademyTrainingSlugRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/academy/training/allocated-zones-for-aquaculture': {
      id: '/academy/training/allocated-zones-for-aquaculture'
      path: '/training/allocated-zones-for-aquaculture'
      fullPath: '/academy/training/allocated-zones-for-aquaculture'
      preLoaderRoute: typeof AcademyTrainingAllocatedZonesForAquacultureRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/events/calls/$slug': {
      id: '/events/calls/$slug'
      path: '/calls/$slug'
      fullPath: '/events/calls/$slug'
      preLoaderRoute: typeof EventsCallsSlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/events/category/$slug': {
      id: '/events/category/$slug'
      path: '/category/$slug'
      fullPath: '/events/category/$slug'
      preLoaderRoute: typeof EventsCategorySlugRouteImport
      parentRoute: typeof EventsRoute
    }
    '/experts/portal/': {
      id: '/experts/portal/'
      path: '/'
      fullPath: '/experts/portal/'
      preLoaderRoute: typeof ExpertsPortalIndexRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/analytics': {
      id: '/experts/portal/analytics'
      path: '/analytics'
      fullPath: '/experts/portal/analytics'
      preLoaderRoute: typeof ExpertsPortalAnalyticsRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/certificates': {
      id: '/experts/portal/certificates'
      path: '/certificates'
      fullPath: '/experts/portal/certificates'
      preLoaderRoute: typeof ExpertsPortalCertificatesRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/portfolio': {
      id: '/experts/portal/portfolio'
      path: '/portfolio'
      fullPath: '/experts/portal/portfolio'
      preLoaderRoute: typeof ExpertsPortalPortfolioRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/recognition': {
      id: '/experts/portal/recognition'
      path: '/recognition'
      fullPath: '/experts/portal/recognition'
      preLoaderRoute: typeof ExpertsPortalRecognitionRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/review-status': {
      id: '/experts/portal/review-status'
      path: '/review-status'
      fullPath: '/experts/portal/review-status'
      preLoaderRoute: typeof ExpertsPortalReviewStatusRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/service-requests': {
      id: '/experts/portal/service-requests'
      path: '/service-requests'
      fullPath: '/experts/portal/service-requests'
      preLoaderRoute: typeof ExpertsPortalServiceRequestsRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/experts/portal/submit-module': {
      id: '/experts/portal/submit-module'
      path: '/submit-module'
      fullPath: '/experts/portal/submit-module'
      preLoaderRoute: typeof ExpertsPortalSubmitModuleRouteImport
      parentRoute: typeof ExpertsPortalRoute
    }
    '/governance/audit/$subjectId': {
      id: '/governance/audit/$subjectId'
      path: '/audit/$subjectId'
      fullPath: '/governance/audit/$subjectId'
      preLoaderRoute: typeof GovernanceAuditSubjectIdRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/subject/$id': {
      id: '/governance/subject/$id'
      path: '/subject/$id'
      fullPath: '/governance/subject/$id'
      preLoaderRoute: typeof GovernanceSubjectIdRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/subjects/': {
      id: '/governance/subjects/'
      path: '/subjects'
      fullPath: '/governance/subjects/'
      preLoaderRoute: typeof GovernanceSubjectsIndexRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/subjects/$id': {
      id: '/governance/subjects/$id'
      path: '/subjects/$id'
      fullPath: '/governance/subjects/$id'
      preLoaderRoute: typeof GovernanceSubjectsIdRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/templates/': {
      id: '/governance/templates/'
      path: '/templates'
      fullPath: '/governance/templates/'
      preLoaderRoute: typeof GovernanceTemplatesIndexRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/governance/templates/$id': {
      id: '/governance/templates/$id'
      path: '/templates/$id'
      fullPath: '/governance/templates/$id'
      preLoaderRoute: typeof GovernanceTemplatesIdRouteImport
      parentRoute: typeof GovernanceRoute
    }
    '/knowledge-hub_/resource/$id': {
      id: '/knowledge-hub_/resource/$id'
      path: '/knowledge-hub/resource/$id'
      fullPath: '/knowledge-hub/resource/$id'
      preLoaderRoute: typeof KnowledgeHubResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AcademyLearnRouteChildren {
  AcademyLearnIdRoute: typeof AcademyLearnIdRoute
  AcademyLearnAllocatedZonesForAquacultureRoute: typeof AcademyLearnAllocatedZonesForAquacultureRoute
  AcademyLearnIndexRoute: typeof AcademyLearnIndexRoute
}

const AcademyLearnRouteChildren: AcademyLearnRouteChildren = {
  AcademyLearnIdRoute: AcademyLearnIdRoute,
  AcademyLearnAllocatedZonesForAquacultureRoute:
    AcademyLearnAllocatedZonesForAquacultureRoute,
  AcademyLearnIndexRoute: AcademyLearnIndexRoute,
}

const AcademyLearnRouteWithChildren = AcademyLearnRoute._addFileChildren(
  AcademyLearnRouteChildren,
)

interface AcademySelfPacedRouteChildren {
  AcademySelfPacedCodeRoute: typeof AcademySelfPacedCodeRoute
}

const AcademySelfPacedRouteChildren: AcademySelfPacedRouteChildren = {
  AcademySelfPacedCodeRoute: AcademySelfPacedCodeRoute,
}

const AcademySelfPacedRouteWithChildren =
  AcademySelfPacedRoute._addFileChildren(AcademySelfPacedRouteChildren)

interface AcademyRouteChildren {
  AcademyAlumniNetworkRoute: typeof AcademyAlumniNetworkRoute
  AcademyArchiveRoute: typeof AcademyArchiveRoute
  AcademyCertificationRoute: typeof AcademyCertificationRoute
  AcademyEdition2024Route: typeof AcademyEdition2024Route
  AcademyLearnRoute: typeof AcademyLearnRouteWithChildren
  AcademyProgramsRoute: typeof AcademyProgramsRoute
  AcademyRequestTrainingRoute: typeof AcademyRequestTrainingRoute
  AcademySelfPacedRoute: typeof AcademySelfPacedRouteWithChildren
  AcademyWebinarRoute: typeof AcademyWebinarRoute
  AcademyWorkshopRoute: typeof AcademyWorkshopRoute
  AcademyIndexRoute: typeof AcademyIndexRoute
  AcademyAlumniIdRoute: typeof AcademyAlumniIdRoute
  AcademyApplicationsIdRoute: typeof AcademyApplicationsIdRoute
  AcademyApplySlugRoute: typeof AcademyApplySlugRoute
  AcademyCategorySlugRoute: typeof AcademyCategorySlugRoute
  AcademyCourseOfferingIdRoute: typeof AcademyCourseOfferingIdRoute
  AcademyPathwaysSlugRoute: typeof AcademyPathwaysSlugRoute
  AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute: typeof AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute
  AcademyShortCoursesCodeRoute: typeof AcademyShortCoursesCodeRoute
  AcademyTrainingRequestsIdRoute: typeof AcademyTrainingRequestsIdRoute
  AcademyTrainingSlugRoute: typeof AcademyTrainingSlugRoute
  AcademyTrainingAllocatedZonesForAquacultureRoute: typeof AcademyTrainingAllocatedZonesForAquacultureRoute
  AcademyAlumniIndexRoute: typeof AcademyAlumniIndexRoute
  AcademyApplicationsIndexRoute: typeof AcademyApplicationsIndexRoute
  AcademyPathwaysIndexRoute: typeof AcademyPathwaysIndexRoute
  AcademyShortCoursesIndexRoute: typeof AcademyShortCoursesIndexRoute
  AcademyTrainingRequestsIndexRoute: typeof AcademyTrainingRequestsIndexRoute
  AcademyTrainingIndexRoute: typeof AcademyTrainingIndexRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyAlumniNetworkRoute: AcademyAlumniNetworkRoute,
  AcademyArchiveRoute: AcademyArchiveRoute,
  AcademyCertificationRoute: AcademyCertificationRoute,
  AcademyEdition2024Route: AcademyEdition2024Route,
  AcademyLearnRoute: AcademyLearnRouteWithChildren,
  AcademyProgramsRoute: AcademyProgramsRoute,
  AcademyRequestTrainingRoute: AcademyRequestTrainingRoute,
  AcademySelfPacedRoute: AcademySelfPacedRouteWithChildren,
  AcademyWebinarRoute: AcademyWebinarRoute,
  AcademyWorkshopRoute: AcademyWorkshopRoute,
  AcademyIndexRoute: AcademyIndexRoute,
  AcademyAlumniIdRoute: AcademyAlumniIdRoute,
  AcademyApplicationsIdRoute: AcademyApplicationsIdRoute,
  AcademyApplySlugRoute: AcademyApplySlugRoute,
  AcademyCategorySlugRoute: AcademyCategorySlugRoute,
  AcademyCourseOfferingIdRoute: AcademyCourseOfferingIdRoute,
  AcademyPathwaysSlugRoute: AcademyPathwaysSlugRoute,
  AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute:
    AcademyPreviewInternationalTrainingFisheriesAfricanCountriesRoute,
  AcademyShortCoursesCodeRoute: AcademyShortCoursesCodeRoute,
  AcademyTrainingRequestsIdRoute: AcademyTrainingRequestsIdRoute,
  AcademyTrainingSlugRoute: AcademyTrainingSlugRoute,
  AcademyTrainingAllocatedZonesForAquacultureRoute:
    AcademyTrainingAllocatedZonesForAquacultureRoute,
  AcademyAlumniIndexRoute: AcademyAlumniIndexRoute,
  AcademyApplicationsIndexRoute: AcademyApplicationsIndexRoute,
  AcademyPathwaysIndexRoute: AcademyPathwaysIndexRoute,
  AcademyShortCoursesIndexRoute: AcademyShortCoursesIndexRoute,
  AcademyTrainingRequestsIndexRoute: AcademyTrainingRequestsIndexRoute,
  AcademyTrainingIndexRoute: AcademyTrainingIndexRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface AccountRouteChildren {
  AccountProfileRoute: typeof AccountProfileRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountProfileRoute: AccountProfileRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminRouteChildren {
  AdminExpertsRoute: typeof AdminExpertsRoute
  AdminModulesRoute: typeof AdminModulesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminExpertsRoute: AdminExpertsRoute,
  AdminModulesRoute: AdminModulesRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsSlugRoute: typeof EventsSlugRoute
  EventsAllRoute: typeof EventsAllRoute
  EventsCalendarRoute: typeof EventsCalendarRoute
  EventsCategoriesRoute: typeof EventsCategoriesRoute
  EventsFollowingRoute: typeof EventsFollowingRoute
  EventsHostRoute: typeof EventsHostRoute
  EventsPastRoute: typeof EventsPastRoute
  EventsRegistrationsRoute: typeof EventsRegistrationsRoute
  EventsSavedRoute: typeof EventsSavedRoute
  EventsScheduleRoute: typeof EventsScheduleRoute
  EventsSubmitRoute: typeof EventsSubmitRoute
  EventsIndexRoute: typeof EventsIndexRoute
  EventsCallsSlugRoute: typeof EventsCallsSlugRoute
  EventsCategorySlugRoute: typeof EventsCategorySlugRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsSlugRoute: EventsSlugRoute,
  EventsAllRoute: EventsAllRoute,
  EventsCalendarRoute: EventsCalendarRoute,
  EventsCategoriesRoute: EventsCategoriesRoute,
  EventsFollowingRoute: EventsFollowingRoute,
  EventsHostRoute: EventsHostRoute,
  EventsPastRoute: EventsPastRoute,
  EventsRegistrationsRoute: EventsRegistrationsRoute,
  EventsSavedRoute: EventsSavedRoute,
  EventsScheduleRoute: EventsScheduleRoute,
  EventsSubmitRoute: EventsSubmitRoute,
  EventsIndexRoute: EventsIndexRoute,
  EventsCallsSlugRoute: EventsCallsSlugRoute,
  EventsCategorySlugRoute: EventsCategorySlugRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface ExpertsPortalRouteChildren {
  ExpertsPortalAnalyticsRoute: typeof ExpertsPortalAnalyticsRoute
  ExpertsPortalCertificatesRoute: typeof ExpertsPortalCertificatesRoute
  ExpertsPortalPortfolioRoute: typeof ExpertsPortalPortfolioRoute
  ExpertsPortalRecognitionRoute: typeof ExpertsPortalRecognitionRoute
  ExpertsPortalReviewStatusRoute: typeof ExpertsPortalReviewStatusRoute
  ExpertsPortalServiceRequestsRoute: typeof ExpertsPortalServiceRequestsRoute
  ExpertsPortalSubmitModuleRoute: typeof ExpertsPortalSubmitModuleRoute
  ExpertsPortalIndexRoute: typeof ExpertsPortalIndexRoute
}

const ExpertsPortalRouteChildren: ExpertsPortalRouteChildren = {
  ExpertsPortalAnalyticsRoute: ExpertsPortalAnalyticsRoute,
  ExpertsPortalCertificatesRoute: ExpertsPortalCertificatesRoute,
  ExpertsPortalPortfolioRoute: ExpertsPortalPortfolioRoute,
  ExpertsPortalRecognitionRoute: ExpertsPortalRecognitionRoute,
  ExpertsPortalReviewStatusRoute: ExpertsPortalReviewStatusRoute,
  ExpertsPortalServiceRequestsRoute: ExpertsPortalServiceRequestsRoute,
  ExpertsPortalSubmitModuleRoute: ExpertsPortalSubmitModuleRoute,
  ExpertsPortalIndexRoute: ExpertsPortalIndexRoute,
}

const ExpertsPortalRouteWithChildren = ExpertsPortalRoute._addFileChildren(
  ExpertsPortalRouteChildren,
)

interface ExpertsRouteChildren {
  ExpertsSlugRoute: typeof ExpertsSlugRoute
  ExpertsBecomeTrainerRoute: typeof ExpertsBecomeTrainerRoute
  ExpertsContributionsRoute: typeof ExpertsContributionsRoute
  ExpertsDirectoryRoute: typeof ExpertsDirectoryRoute
  ExpertsFaqsRoute: typeof ExpertsFaqsRoute
  ExpertsJoinRoute: typeof ExpertsJoinRoute
  ExpertsMyRequestsRoute: typeof ExpertsMyRequestsRoute
  ExpertsPortalRoute: typeof ExpertsPortalRouteWithChildren
  ExpertsProfileRoute: typeof ExpertsProfileRoute
  ExpertsRecognitionRoute: typeof ExpertsRecognitionRoute
  ExpertsRequestRoute: typeof ExpertsRequestRoute
  ExpertsServicesRoute: typeof ExpertsServicesRoute
  ExpertsIndexRoute: typeof ExpertsIndexRoute
}

const ExpertsRouteChildren: ExpertsRouteChildren = {
  ExpertsSlugRoute: ExpertsSlugRoute,
  ExpertsBecomeTrainerRoute: ExpertsBecomeTrainerRoute,
  ExpertsContributionsRoute: ExpertsContributionsRoute,
  ExpertsDirectoryRoute: ExpertsDirectoryRoute,
  ExpertsFaqsRoute: ExpertsFaqsRoute,
  ExpertsJoinRoute: ExpertsJoinRoute,
  ExpertsMyRequestsRoute: ExpertsMyRequestsRoute,
  ExpertsPortalRoute: ExpertsPortalRouteWithChildren,
  ExpertsProfileRoute: ExpertsProfileRoute,
  ExpertsRecognitionRoute: ExpertsRecognitionRoute,
  ExpertsRequestRoute: ExpertsRequestRoute,
  ExpertsServicesRoute: ExpertsServicesRoute,
  ExpertsIndexRoute: ExpertsIndexRoute,
}

const ExpertsRouteWithChildren =
  ExpertsRoute._addFileChildren(ExpertsRouteChildren)

interface GovernanceRouteChildren {
  GovernanceDecisionsRoute: typeof GovernanceDecisionsRoute
  GovernanceQueueRoute: typeof GovernanceQueueRoute
  GovernanceRolesRoute: typeof GovernanceRolesRoute
  GovernanceIndexRoute: typeof GovernanceIndexRoute
  GovernanceAuditSubjectIdRoute: typeof GovernanceAuditSubjectIdRoute
  GovernanceSubjectIdRoute: typeof GovernanceSubjectIdRoute
  GovernanceSubjectsIdRoute: typeof GovernanceSubjectsIdRoute
  GovernanceTemplatesIdRoute: typeof GovernanceTemplatesIdRoute
  GovernanceSubjectsIndexRoute: typeof GovernanceSubjectsIndexRoute
  GovernanceTemplatesIndexRoute: typeof GovernanceTemplatesIndexRoute
}

const GovernanceRouteChildren: GovernanceRouteChildren = {
  GovernanceDecisionsRoute: GovernanceDecisionsRoute,
  GovernanceQueueRoute: GovernanceQueueRoute,
  GovernanceRolesRoute: GovernanceRolesRoute,
  GovernanceIndexRoute: GovernanceIndexRoute,
  GovernanceAuditSubjectIdRoute: GovernanceAuditSubjectIdRoute,
  GovernanceSubjectIdRoute: GovernanceSubjectIdRoute,
  GovernanceSubjectsIdRoute: GovernanceSubjectsIdRoute,
  GovernanceTemplatesIdRoute: GovernanceTemplatesIdRoute,
  GovernanceSubjectsIndexRoute: GovernanceSubjectsIndexRoute,
  GovernanceTemplatesIndexRoute: GovernanceTemplatesIndexRoute,
}

const GovernanceRouteWithChildren = GovernanceRoute._addFileChildren(
  GovernanceRouteChildren,
)

interface MySubmissionsRouteChildren {
  MySubmissionsIdRoute: typeof MySubmissionsIdRoute
  MySubmissionsNewRoute: typeof MySubmissionsNewRoute
  MySubmissionsIndexRoute: typeof MySubmissionsIndexRoute
}

const MySubmissionsRouteChildren: MySubmissionsRouteChildren = {
  MySubmissionsIdRoute: MySubmissionsIdRoute,
  MySubmissionsNewRoute: MySubmissionsNewRoute,
  MySubmissionsIndexRoute: MySubmissionsIndexRoute,
}

const MySubmissionsRouteWithChildren = MySubmissionsRoute._addFileChildren(
  MySubmissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademyRoute: AcademyRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AnalyticsRoute: AnalyticsRoute,
  AuthRoute: AuthRoute,
  CommunityRoute: CommunityRoute,
  DashboardRoute: DashboardRoute,
  DemoRoute: DemoRoute,
  EventsRoute: EventsRouteWithChildren,
  ExpertsRoute: ExpertsRouteWithChildren,
  FellowshipRoute: FellowshipRoute,
  GovernanceRoute: GovernanceRouteWithChildren,
  HelpRoute: HelpRoute,
  KnowledgeHubRoute: KnowledgeHubRoute,
  MySubmissionsRoute: MySubmissionsRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PartnershipRoute: PartnershipRoute,
  SavedRoute: SavedRoute,
  SearchRoute: SearchRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KnowledgeHubTypeRoute: KnowledgeHubTypeRoute,
  KnowledgeHubMyContributionsRoute: KnowledgeHubMyContributionsRoute,
  KnowledgeHubSubmitResourceRoute: KnowledgeHubSubmitResourceRoute,
  KnowledgeHubResourceIdRoute: KnowledgeHubResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
